### ISSUE TITLE
Y2Mp3.apk shows as NoResult for any search

### ISSUE THREAD

**Issue by maazamode** [moshfeu/y2mp3#102]
**Describe the bug**
Since 04/05/2022, results appear for any search but when click on one result, download shows as No Result :)

**To Reproduce**
1. Open Y2Mp3 Android application
2. Click on 'Downlaod' button
3. Type 'Song About rain'
4. Select the first result 'songs about rain'
5. See error No result

**Add logs from DevTools**

Please go to **y2mp3** menu -> **Toggle Developer Tools** or hit <kbd>ctrl</kbd>+<kbd>Alt</kbd>+<kbd>j</kbd> (on windows) or 
<kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>j</kbd> (on mac), if there are error messages please include them.

**Expected behavior**

**Screenshots**

 - OS: [Android]
 - Version [12]
 - App Version [App version 2.0.55]

**Additional context**

**Comment by moshfeu** [comment]
Hi @maazamode!
There seems to be confusion here. This repository hosts the code of the desktop app "y2mp3", not the android app.
