### ISSUE TITLE
Screen remains green after opening the .appimage.

### ISSUE THREAD

**Issue by aprendiz000** [moshfeu/y2mp3#109]
**Describe the bug**
Screen remains green after opening the .appimage.

**To Reproduce**
1. Open y2mp3-2.5.6.AppImage

**Add logs from DevTools**

Please go to **y2mp3** menu -> **Toggle Developer Tools** or hit <kbd>ctrl</kbd>+<kbd>Alt</kbd>+<kbd>j</kbd> (on windows) or 
<kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>j</kbd> (on mac), if there are error messages please include them.

node:electron/js2c/renderer_init:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ node:electron/js2c/renderer_init:33
node:internal/fs/utils:344 Uncaught Error: ENOENT: no such file or directory, mkdir '/home/shwetank/downloads/y2mp3'
    at mkdirSync (node:fs:1334:3)
    at file:///tmp/.mount_y2mp3-IHVf2T/resources/app.asar/resources/app.bundle.js:2:1928279
    at file:///tmp/.mount_y2mp3-IHVf2T/resources/app.asar/resources/app.bundle.js:2:2096515
    at file:///tmp/.mount_y2mp3-IHVf2T/resources/app.asar/resources/app.bundle.js:2:2096519

**Expected behavior**
Should see app working, but all I see is green screen

**Screenshots**
![Screenshot from 2022-06-16 18-28-16](https://user-images.githubusercontent.com/66858094/174074949-6ec36b5c-f5f9-4332-9237-56421652a535.png)

 - OS: [Ubuntu]
 - Version [20.04.4 LTS]
 - App Version [2.5.6]

**Additional context**

**Comment by moshfeu** [comment]
Thank you for the issue. I'll look into it as soon as I can.
As a workaround, can you create a `downloads` folder under `home/shwetank`? You can change this path afterwards in the settings screen.

**Comment by aprendiz000** [comment]
Thank you. After creating that folder, it worked alright.
