### ISSUE TITLE
Invalid or Unexpected Token

### ISSUE THREAD

**Issue by tokyosinner** [moshfeu/y2mp3#115]
When I press download on any youtube video link, it processes to around 10% and gives the error "invalid or unexpected token."

**Comment by tokyosinner** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/104904375/186588372-828146a3-fd9e-47ed-aa0a-e2eab4fd40e3.png">

**Comment by tokyosinner** [comment]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/104904375/186588769-bfa41f04-2897-497b-8d11-85eae0ddb980.png">

**Comment by moshfeu** [comment]
Thank you for reporting this issue. 
Isn't working for any url or just this one? 
Can you try the url format of youtube.com?
I'll try out the url from your picture asap.

**Comment by tokyosinner** [comment]
Sorry for the delayed response. This issue appears to have resolved itself. The error no longer occurs for me with youtube.com or youtu.be URLs.

When the issue was happening before, it was with any URL, but now everything seems to be working as usual.

Thanks for looking into this! I really appreciate this application and use it often - you've done great work.

**Comment by moshfeu** [comment]
I'm so happy to hear, thank you for letting me know and I'm happy you like y3mp4 😊
