### ISSUE TITLE
Unexpected end of input : Download Failed!!!

### ISSUE THREAD

**Issue by rommansabbir** [moshfeu/y2mp3#120]
**Describe the bug**

**To Reproduce**
1. Go to 'Submit any YT link'
2. Click on 'download'
3. Scroll down to 'chose any format'

**Add logs from DevTools**

Please go to **y2mp3** menu -> **Toggle Developer Tools** or hit <kbd>ctrl</kbd>+<kbd>Alt</kbd>+<kbd>j</kbd> (on windows) or 
<kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>j</kbd> (on mac), if there are error messages please include them.

```
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
Content Security Policy of your site blocks the use of 'eval' in JavaScript`
```
![image](https://user-images.githubusercontent.com/25950083/212478508-66c3674b-42b2-4f2e-bba8-307ed051f1dd.png)

**Expected behavior**

Download properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/25950083/212478357-175eec72-cf76-4905-add7-c6c663015597.png)

![image](https://user-images.githubusercontent.com/25950083/212478662-b79deabb-6133-497c-a3e7-692526db63f2.png)

 - OS: Windows
 - Version: 10 Pro
 - App Version: 2.5.6

**Additional context**

**Comment by moshfeu** [comment]
Thank you for letting me know.
I've just tried and it's working for me now (on mac). Can you check again? Maybe it was a one time issue?
If not, can you try another video to see if there is an issue with this one?

**Comment by gustavolanzas** [comment]
Hello, I'm on Mac OSX Mojave 10.14.6, using release 2.5.6 and have the same issue that Romman reported, although I get one additional error (uncaught typeError). Here's my console output:

![Screen Shot 2023-01-14 at 12 14 17 PM](https://user-images.githubusercontent.com/1471172/212494587-ebcbae6e-71c1-4356-a2c5-a60b8562a737.png)

**Comment by moshfeu** [comment]
I see the error in my end too.
Can you test [v2.5.5](https://github.com/moshfeu/y2mp3/releases/tag/v2.5.5) for now until I will figure it out?

**Comment by gustavolanzas** [comment]
Thanks @moshfeu, 2.5.5 worked. I am still seeing the yellow warning with ytdl-core, but it is successfully downloading videos.

**Comment by moshfeu** [comment]
Just released [v2.5.7](https://github.com/moshfeu/y2mp3/releases/tag/v2.5.7) and verified that it's working.
Can you guys check if it's working for you?

**Comment by rommansabbir** [comment]
![image](https://user-images.githubusercontent.com/25950083/230659415-6fff0db9-b5b9-44b1-9e48-5de29dd5ddc6.png)

![image](https://user-images.githubusercontent.com/25950083/230659749-46bb1840-e63e-437e-a386-570515f537fd.png)

![image](https://user-images.githubusercontent.com/25950083/230659643-234e05f9-4438-4f26-9cfa-66d782acd70d.png)


Version: 2.5.7
OS: Windows 10 Pro

**Comment by moshfeu** [comment]
Hi @rommansabbir can you try the latest version - https://github.com/moshfeu/y2mp3/releases/tag/v2.5.8 please?

**Comment by rommansabbir** [comment]
Yes, working fine! Thank you.

**Comment by moshfeu** [comment]
You are welcome ☺️

**Comment by rommansabbir** [comment]
![image](https://github.com/moshfeu/y2mp3/assets/25950083/05e5560f-2518-4f87-9008-98c3df6456b9)

Version: 2.5.8
OS: Windows 10 Pro 22H2 (19045.3324)

**Comment by rommansabbir** [comment]
Same behavior in Version: 2.5.9-alpha

**Comment by moshfeu** [comment]
A fix is on its way. Thanks for reporting (again)

**Comment by moshfeu** [comment]
Troubles with releasing the app.
Can you try with the latest version? Tried on Mac

**Comment by rommansabbir** [comment]
Hi, working as expected but taking too much time to download. 


![image](https://github.com/moshfeu/y2mp3/assets/25950083/d27f99b6-0403-41f6-a7ad-ea60a4596d0c)

**Comment by moshfeu** [comment]
Are you sure that it's not related to the general network speed? There is nothing between the app and YouTube server so I think that the app's based on the local internet connection speed and YouTube responsiveness

**Comment by rommansabbir** [comment]
I've taken the liberty of testing with a different network, and unfortunately, the download speed remains quite low. However, I did discover an alternative mobile app called 'YMusic' that seems to offer significantly faster download speeds. It's possible that this app utilizes the same API as the one you're using

**Comment by moshfeu** [comment]
Thanks for diving into this research, really appreciated.

Can you share with me a url you downloaded, what file format and quality and how much time it took to download?

I don't know how this app was implemented therefore I don't know if y2mp3 can adopt any of their improvements.
Maybe they have their own server that stores and caches the resources from YouTube so if 2 people are asking for the same resource, the second user will get it faster. 
This is not how y2mp3 works. The app connects YouTube servers directly.

**Comment by rommansabbir** [comment]
Here is the YT Link: https://www.youtube.com/watch?v=cDLL8FHhLc8

**Comment by rommansabbir** [comment]
Facing this issue while downloading.

Version: 2.5.8
OS: Mac OS (Ventura 13.0)
Device: Apple M1 Pro

![image](https://github.com/moshfeu/y2mp3/assets/25950083/b48313e1-c8dd-477a-93aa-22375d02c997)

**Comment by moshfeu** [comment]
Thanks for letting me know.
I see it in my console too but I'm not sure why. I think that the icon has been required for the notification icon, it's the only one whose using the _logo-128.png_. I'd expect that the icon will be missing in the notification bubble but it's not, it's there.

Can you tell me if you are seeing the green logo of y2mp3 in the notification bubble?

**Comment by rommansabbir** [comment]
I'm not sure.

**Comment by moshfeu** [comment]
I mean this icon

<img width="472" alt="image" src="https://github.com/moshfeu/y2mp3/assets/3723951/1bafae99-707e-4ce5-bd31-c3a47645df9a">

**Comment by rommansabbir** [comment]
Yes, the icon is present in the top bar.

**Comment by rommansabbir** [comment]
` GET file:///Applications/y2mp3.app/Contents/Resources/app.asar/app-resources/logo-128.png net::ERR_FILE_NOT_FOUND `

**Comment by moshfeu** [comment]
So I'm not sure what's the impact of this error. The icon in the top bar is the only place I know that uses this image.
Anyway, if you notice an unexpected user experience regarding this icon, please let me know

**Comment by rommansabbir** [comment]
Actually I'm also not sure about the impact.

**Comment by moshfeu** [comment]
Me neither :) I couldn't find the impact

**Comment by rommansabbir** [comment]
Okay.
