### ISSUE TITLE
missing catch or finally after try

### ISSUE THREAD

**Issue by spy64bit** [moshfeu/y2mp3#127]
**Describe the bug**
After click on download, it show "missing catch or finally after try"

**To Reproduce**
1. paste YT link.'
2. Click on 'download'
3. See error

**Add logs from DevTools**

Please go to **y2mp3** menu -> **Toggle Developer Tools** or hit <kbd>ctrl</kbd>+<kbd>Alt</kbd>+<kbd>j</kbd> (on windows) or 
<kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>j</kbd> (on mac), if there are error messages please include them.

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at Object.t.decipherFormats (file:///C:/Users/Night/AppData/Local/Programs/y2mp3/resources/app.asar/resources/app.bundle.js:2:1430236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async t.getInfo (file:///C:/Users/Night/AppData/Local/Programs/y2mp3/resources/app.asar/resources/app.bundle.js:2:1427178)
![y2mp3error](https://user-images.githubusercontent.com/126850311/230950245-87a3984f-efa7-45b8-8aac-f98f35f908e7.png)

**Expected behavior**
The Video or audio file didn't download

**Screenshots**

 - OS: Windows
 - Version 10 Pro
 - App Version v2.5.8

**Additional context**

**Comment by moshfeu** [comment]
What's the url you are trying to download?

**Comment by spy64bit** [comment]
https://www.youtube.com/watch?v=52fGG37_0_E
i also try on other url, it show the same error

**Comment by moshfeu** [comment]
Seems like it's a problem with the downloading package which affects windows devices


Can you try the [pre-release](https://github.com/moshfeu/y2mp3/releases/tag/v2.5.9-alpha) version please?

**Comment by moshfeu** [comment]
It's a problem with one of the core packages

https://github.com/fent/node-ytdl-core/issues/1204

Please try the following version: https://github.com/moshfeu/y2mp3/releases/tag/v2.5.9-alpha

**Comment by spy64bit** [comment]
It's working now. thx =D
