### ISSUE TITLE
y2mp3 can not download playlists

### ISSUE THREAD

**Issue by JanPeterBalkenende** [moshfeu/y2mp3#131]
**Describe the bug**
When inserting a link to a video playlist (whether unlisted or public) and hitting the search icon, the magnifying glass tilts a bit, but no download button pops up.

**Steps to reproduce the behavior:**

1. Open the application
2. Insert link to playlist
3. Hit search

![ezgif-1-d82f81df2d](https://github.com/moshfeu/y2mp3/assets/70443401/9b32dfe1-819d-4570-bb03-51e0b5917c2f)

**Comment by moshfeu** [comment]
Thanks for reporting 🙏
I'll check that as soon as I have time.
Meantime, can you toggle the developer tool and see if there is an error in the console? I think that you can find this option under "view"

**Comment by JanPeterBalkenende** [comment]
Thanks for the swift reply! Apparently it's a 403 error. The playlist is accessible from a private browsing session that's logged out, so with my limited knowledge I don't know why it would be forbidden. Here's the console output:

![image](https://github.com/moshfeu/y2mp3/assets/70443401/38ffd40a-7156-4e42-b40a-fdd1e1f7f1f6)

**Comment by moshfeu** [comment]
Thanks for details!
Can you share the playlist url please? I'll try to debug it locally
Anyway, the app should show an error in such cases. I'll add it

**Comment by JanPeterBalkenende** [comment]
Here's the link:

https://www.youtube.com/playlist?list=PLhAn7HLECtymvWV9QaDGNYpq-4xwgJl6e

Thanks for the help! I am curious as to what the issue is

**Comment by moshfeu** [comment]
Oh come on.. It's working for me

https://github.com/moshfeu/y2mp3/assets/3723951/78c3c27c-f958-4d16-b060-dcfd09f0d4ce

Maybe it's more local, blocked by country or VPN settings
Maybe if you click on the link in the console you'll see what youtube try to say

**Comment by JanPeterBalkenende** [comment]
Ah the link redirects me to a page on which I have to either accept or reject cookies.
Any idea how to get around this?

Thanks eitherway!

**Comment by moshfeu** [comment]
Was it working for you in the before? Is this the first time you are trying to download?

**Comment by JanPeterBalkenende** [comment]
This is my first time using this software.

Interestingly enough, downloading individual videos does work

**Comment by moshfeu** [comment]
First, welcome :) I'm curious, how did you find y2mp3?
Fetching a playlist data and downloading a video are handled differently (downloading a video code (which isn't written by me, I'm using a library) is way more advanced than fetching the playlist data code so it might handle this kind of case

It's odd! When you try to access the playlist page in Incognito you don't get into the cookies approval page?
Have you tried another playlists link?

If youtube stores the user consent in a cookie, maybe I can add an option in the app to set cookies so it would pass that cookie to Youtube so Youtube would skip this page. Out of curiosity can you [review the cookies](https://developer.chrome.com/docs/devtools/application/cookies) in Youtube and see if something pops out? (I don't want you to post the cookies here in case there is a sensitive data there)

**Comment by moshfeu** [comment]
>Out of curiosity can you [review the cookies](https://developer.chrome.com/docs/devtools/application/cookies) in Youtube and see if something pops out?

Maybe the `SOCS` cookie?

https://stackoverflow.com/a/74132453/863110

**Comment by JanPeterBalkenende** [comment]
> First, welcome :) I'm curious, how did you find y2mp3?

Thanks for the warm welcome! I literally just googled "Open source Youtube - mp3 converter" and this was the only GUI based non-deprecated one (I am a bash man and not a powershell man).

> It's odd! When you try to access the playlist page in Incognito you don't get into the cookies approval page?
> Have you tried another playlists link?

I do get the cookie page for any playlist I try, yes

> Out of curiosity can you [review the cookies](https://developer.chrome.com/docs/devtools/application/cookies) in Youtube and see if something pops out?

My lord, I have 2.6GiB of cookies for YouTube alone... One of them is a SOCS cookie indeed. However, deleting the SOCS cookie and opening a playlist in a new tab does not prompt me with the cookie screen.

However if I open up an private window, and open Youtube, I only have 5-6 cookies and get prompted with a cookie window. If I deny it I get a SOCS cookie. if I accept it, I get a SOCS and GPS cookie. Maybe you're onto something with setting cookies in the app.

Also, maybe this issue is replicable if you use a VPN and set it to a country within the EU, as I think we have some of the strictest cookie restrictions here.

Thanks for the help!

**Comment by moshfeu** [comment]
I think I was able to bypass the consent screen. Can you try please?

Find the download here: https://github.com/moshfeu/y2mp3/releases/tag/v2.5.11-alpha
