### ISSUE TITLE
Status Code : 403

### ISSUE THREAD

**Issue by rommansabbir** [moshfeu/y2mp3#137]
**Describe the bug**
Downloads returns Status Code : 403

**To Reproduce**
Paste url, click download, and error

**Add logs from DevTools**
Full logs added

**Expected behavior**
Should download

**Screenshots**
![Screenshot_24](https://github.com/user-attachments/assets/f41fe8f9-308e-4695-a9b1-b33070299946)

 - OS: Win 10
 - Version --
 - App Version 2.6.1

**Additional context**
Complete Log:

[-1727458919302.log](https://github.com/user-attachments/files/17167774/-1727458919302.log)

**Comment by moshfeu** [comment]
Thank you for reporting. Seems like there is a problem with the library that fetches the video
I'll push a fix as soon as they deliver a fix on their side

https://github.com/fent/node-ytdl-core/issues/1313

**Comment by moshfeu** [comment]
Released the fix under [3.0.0](https://github.com/moshfeu/y2mp3/releases/tag/v3.0.0)

**Comment by rommansabbir** [comment]
Same issue on Version: 3.0.1. Status Code: 403
