### ISSUE TITLE
Save to a playlist folder

### ISSUE THREAD

**Issue by saydax** [moshfeu/y2mp3#25]
The program is really excellent

I think it might be a great feature to automatically save a playlist in a folder.

**Comment by moshfeu** [comment]
Thanks! I'm happy you like it. What do you mean by "save a playlist in a folder"? To save each playlist to a dedicated folder so the users wouldn't have to create the folder by themselves?

**Comment by saydax** [comment]
That's exactly what I say.

**Comment by moshfeu** [comment]
Interesting! Would you want to develop this?

**Comment by moshfeu** [comment]
@saydax Are you a frontend developer? If you want to take this issue, that will be great :) If not, it's totally ok. Usually the first privilege for taking an issue goes to the reporter.

**Comment by moshfeu** [comment]
Added. Let me know what you think.
Thanks!
