### ISSUE TITLE
Click "Downloads Folder Icon Select" in preferences open many windows 

### ISSUE THREAD

**Issue by iahmedhendi** [moshfeu/y2mp3#31]
**Describe the bug**
Click "Downloads Folder Icon Select" in preferences open many windows every click open a new window 
**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Dowloads Folder icon'
 
 
**Expected behavior**
Select Downloads Folder window open once  but it open a new window over old one every time you click the icon

**Comment by moshfeu** [comment]
Thank you for reporting!
Definitely will be resolved in the next version.

**Comment by moshfeu** [comment]
Can I tag you in a tweet about the new version? If so, what's your twitter id?
Thanks

**Comment by iahmedhendi** [comment]
sure
@iahmedhendi

**Comment by moshfeu** [comment]
Thanks
