### ISSUE TITLE
check for update every time app opened!

### ISSUE THREAD

**Issue by iahmedhendi** [moshfeu/y2mp3#40]
I suggest to add check for updates every time app opened 
I was have **version 1.7** and it didn't work correct and I thought that app support stopped or terminated but I checked the github to discover that the **current version is 2.1** and i miss the update. 
Please make a check for update option it will be great!

**Comment by moshfeu** [comment]
Thanks! Will be in the next version (Which you will have to check manually 😀)

**Comment by moshfeu** [comment]
Published. Thanks! https://github.com/moshfeu/y2mp3/releases/tag/v2.1.0
