### ISSUE TITLE
Youtube List Download

### ISSUE THREAD

**Issue by oguzsaka** [moshfeu/y2mp3#53]
Can you create a folder with automatic list name while downloading the Youtube list?

**Comment by moshfeu** [comment]
Do you mean for that option?

<img width="473" alt="Screen Shot 2019-12-02 at 18 19 04" src="https://user-images.githubusercontent.com/3723951/69975702-56f91780-1530-11ea-9445-a9af411f8931.png">

**Comment by oguzsaka** [comment]
I'm sorry I didn't see it

**Comment by moshfeu** [comment]
This is actually a great feedback. I should re-thinking of that screen.
