### ISSUE TITLE
DOWNLOAD NOT WORKİNG

### ISSUE THREAD

**Issue by oguzsaka** [moshfeu/y2mp3#54]
![SS](https://user-images.githubusercontent.com/7862838/72626092-16782080-395b-11ea-827b-5a7f856349ca.PNG)

FFMPEG UPDATE  BUT NOT WORKİNG

**Comment by moshfeu** [comment]
Seems like it's a bug in ytdl: https://github.com/fent/node-ytdl-core/issues/538.
Updating the package solved the problem.
Fix will be available in v2.4.1

**Comment by oguzsaka** [comment]
thanks :)

**Comment by moshfeu** [comment]
Thank you for reporting!

**Comment by oguzsaka** [comment]
Update readme.md v2.4.1

**Comment by moshfeu** [comment]
Exactly what I did :)
I drafted the new version. Can you verify the fix?
Thanks

https://github.com/moshfeu/y2mp3/releases/tag/untagged-b671211498154642c4fc

**Comment by oguzsaka** [comment]
thanks :)
https://electronjs.org/apps/y2mp3 link is not working old
you don't want to show corrupt software for new users

**Comment by moshfeu** [comment]
Yes.
The link I sent in the last comment is to "draft" - not official version so we could test it before release it to all.
Is that version working for you?

**Comment by oguzsaka** [comment]
I was trying my python project, I could not try it, I am trying now

**Comment by moshfeu** [comment]
Sorry, I didn't notice that draft versions are not available.
I marked it as "pre-release" so now you can test it: https://github.com/moshfeu/y2mp3/releases/tag/v2.4.1.

Thanks

**Comment by oguzsaka** [comment]
![sss](https://user-images.githubusercontent.com/7862838/72671082-49eba580-3a56-11ea-84b2-0b43faf7afb8.PNG)
How can I solve this? Do you have any suggestions?

**Comment by moshfeu** [comment]
https://github.com/angular/angular/issues/13935#issuecomment-370875459 maybe?

**Comment by moshfeu** [comment]
Try to remove _node_modules_ and `yarn` maybe?
