### ISSUE TITLE
Bug Report: Setup doesn't work

### ISSUE THREAD

**Issue by NiklasEsser** [moshfeu/y2mp3#73]
**Describe the bug**
The setup v2.5.3 doesn't work to install the program correctly.

**To Reproduce**
1. Go to 'https://github.com/moshfeu/y2mp3/releases/tag/v2.5.3'
2. Click on 'y2mp3.Setup.2.5.3.exe'
3. Start the download
4. Execute/Double-Click the program 'y2mp3.Setup.2.5.3.exe'
5. Wait until the installation has completed
6. See error

**Expected behavior**
This error message.
![Bug](https://user-images.githubusercontent.com/40426398/115989279-ebe53080-a5bd-11eb-8aab-8b11d39e3958.jpg)

**Comment by NiklasEsser** [comment]
First of all I don't like the comma behind ipcMain because i have some coding experiences but not in JavaScript. Just as a hint.

**Comment by moshfeu** [comment]
Can you download and try 2.5.4 please?
Thanks!

https://github.com/moshfeu/y2mp3/releases/tag/v2.5.4

**Comment by NiklasEsser** [comment]
Thank you, now it works but I have a next problem that I haven't a search field.

![NewBug](https://user-images.githubusercontent.com/40426398/116005507-8c137780-a607-11eb-865d-63d0a7c5e83a.jpg)

**Comment by NiklasEsser** [comment]
And I can't open the preferences.

**Comment by moshfeu** [comment]
I think I fixed it. Can you download and test (It's still 2.5.4)?
Thanks!

**Comment by NiklasEsser** [comment]
Thank you very much now it works. I just need to split my playlist with over 1300 songs in many <=100 playlists and I'm happy.

For me is my issue closed because I don't need it but the last thing is that the preference 'Set the video's thumnail as album art (for mp3 only)' not worked.
![NewBug2](https://user-images.githubusercontent.com/40426398/116070140-890e9a80-a68c-11eb-9f3d-4c09c1685866.jpg)

And it is a mp3 file.
![NewBug2-2](https://user-images.githubusercontent.com/40426398/116070198-9b88d400-a68c-11eb-982e-b283b798e27f.jpg)

I let this issue open that you can inform me again to test but no hurry.

**Comment by moshfeu** [comment]
Thanks for the confirmation!
Can you close this one and open a new issue for the album art? Please add the URL you used.
