### ISSUE TITLE
Playlist downloading not working

### ISSUE THREAD

**Issue by lys1980** [moshfeu/y2mp3#76]
Windows App, latest version, when I submit a Youtube playlist URL, nothing happens

**Comment by moshfeu** [comment]
Thank you for the report!

Some questions:
- What is the URL of the playlist?
- Have you tried other playlists?
- What about settings a single clip URL?
- Are you using windows 10? If not, what version?

**Comment by lys1980** [comment]
- What is the URL of the playlist?
   https://www.youtube.com/playlist?list=PL8OA11u18TUqFjgfKKhcrL-tnS8MEOuZ0
   - Have you tried other playlists? yes, and it works
   - What about settings a single clip URL? a single clip of the playlist
   above doesnt work
   - Are you using windows 10? If not, what version? WIn 10


Il giorno sab 1 mag 2021 alle ore 19:54 Mosh Feu ***@***.***>
ha scritto:

**Comment by moshfeu** [comment]
Thanks for the info.

Seems like it happens because the playlist is very big and loads more songs as you scroll.
I'll work on a fix but meanwhile I'd suggest to cut it off if possible.

**Comment by moshfeu** [comment]
I just published a [pr version](https://github.com/moshfeu/y2mp3/releases/tag/v2.5.5). Can you check please?
